import re
from collections import defaultdict
import math
import os
import re
import sys
from matplotlib.colors import LinearSegmentedColormap
import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict
import statistics
import json

FOLDER = "experiment_results/experiment_1min_5rep_laptop/"
#FOLDER = "experiment_results/experiment_20260119_600s_50r/"

BINS = 300
#number of bins for heatmaps
TAGBINS = 50
#number of bins for heatmaps

blue_agents = [0, 1, 2]
red_agents  = [3, 4, 5]

def scancsv(foldername):
    """
    Scans the file extracted_data.json in the given 
    folder and returns a dictionary with the data 
    from each file.
    Expects the json to have been generated by analyze_log function.
    """
    jsonfile = os.path.join(foldername, "extracted_data.json")
    if not os.path.exists(jsonfile):
        raise FileNotFoundError(f"JSON file not found: {jsonfile}")

    data = defaultdict(lambda: defaultdict(list))
    group_positions = defaultdict(lambda: {'blue': [], 'red': [], 'tag': []})
    skipped = []

    metric_cols = [
        "red_score", "blue_score",
        "blue_score_per_tag", "red_score_per_tag", "blue_def_avg_dist", "red_def_avg_dist",
        "blue_agr_avg_dist", "red_agr_avg_dist", "blue_defagr_dist", "red_defagr_dist",
        "blue_total_dist", "red_total_dist", "blue_triangle_area", "red_triangle_area",
        "blue_cover_dist", "red_cover_dist", "blue_sides", "red_sides", "red_voronoi", "blue_voronoi"
    ]

    try:
        with open(jsonfile, 'r') as f:
            entries = json.load(f)
    except Exception as e:
        raise RuntimeError(f"Failed to load JSON: {e}")
    print(f"Loaded {len(entries)} entries from {jsonfile}")
    # loads each game as an entry in a list

    for idx, entry in enumerate(entries):
        try:
            agent_type = str(entry["agent_type"])
            difficulty = entry["difficulty"]
            reward = str(entry["reward"])
            key = (agent_type, difficulty, reward)

            # Parse metrics
            for col in metric_cols:
                val = entry.get(col, None)
                if val is not None:
                    if isinstance(val, list) and val:
                        avg_val = statistics.mean(val)
                    elif isinstance(val, (int, float)):
                        avg_val = float(val)
                    else:
                        avg_val = np.nan
                    data[key][col].append(avg_val)

            # Parse positions
            for pos_type in ["blue_positions", "red_positions"]:
                pos_val = entry.get(pos_type, [])
                if isinstance(pos_val, list):
                    group_positions[key][pos_type.split('_')[0]].extend(pos_val)

            # Parse tag_positions
            tag_val = entry.get("tag_positions", {})
            if isinstance(tag_val, dict):
                group_positions[key]['tag'].append(tag_val)

        except Exception as e:
            skipped.append((f"entry {idx}", str(e)))
    print(f"Processed {len(entries) - len(skipped)} entries, skipped {len(skipped)} due to errors.")

    # Compute averages and prepare final dicts
    averaged = {}
    all_metric_keys = set()
    for key, metrics in data.items():
        averaged[key] = {}
        for metric, values in metrics.items():
            valid_vals = [v for v in values if not np.isnan(v)]
            if valid_vals:
                averaged[key][metric] = statistics.mean(valid_vals)
                averaged[key][metric + '_list'] = valid_vals
                all_metric_keys.add(metric)
                #print(f"Key {key}, Metric {metric}: avg={averaged[key][metric]}, count={len(valid_vals)}")
                #print outputs: Key ('2', 'medium', '2'), Metric red_total_dist: avg=9242.001740331978, count=5
    #print("averaged =",averaged, "group_positions =",group_positions, "all_metric_keys =",all_metric_keys, "skipped =",skipped)
    #print("group_positions example =", {k: v for k, v in list(group_positions.items())[:1]}) #even so is too long to print :/
    #averaged* = ... {('0', 'easy', '1'): {'blue_score_per_tag': 3.5, 'blue_score_per_tag_list': [3.5, 3.5, 3.5, 3.5, 3.5], 'red_score_per_tag': 0.0, 'red_score_per_tag_list': [0.0, 0.0, 0.0, 0.0, 0.0], 'blue_def_avg_dist': 12.3, ...}, ...}
    #group_positions* = defaultdict(<function scancsv.<locals>.<lambda> at 0x7f8c540c1af0>, {('0', 'easy', '1'): {'blue': [[12.3, 23.4], [13.4, 24.5], ...], 'red': [[78.9, 67.8], [79.0, 68.9], ...], 'tag': [{'3': [[45.6, 34.5], [46.7, 35.6], ...],
    # ends definitely in= ... '4': [[32.2, 38.2], [32.7, 37.9], [37.1, 38.4], [25.9, 41.1]], '0': [], '2': []}]}})
    #all_metric_keys = {'red_def_avg_dist', 'blue_defagr_dist', 'blue_def_avg_dist', 'red_score_per_tag', 'red_agr_avg_dist', 'red_total_dist', 'blue_total_dist', 'blue_agr_avg_dist', 'blue_score_per_tag', 'red_defagr_dist'} 
    #skipped should be empty
    return averaged, group_positions, all_metric_keys, skipped

def graphicmaker(foldername):
    """
    Accesses a csv file and makes plots from the data.
    Expects the csv to have been generated by analyze_log function.
    Produces plots and saves them in a subfolder "analysis_plots" 
    inside the given folder.
    """

    averaged, group_positions, all_metric_keys, skipped = scancsv(foldername)

    #print scores for debugging
    #for k in averaged.keys():
    #    print(f"Key {k}: blue_score={averaged[k].get('blue_score', 'N/A')}, red_score={averaged[k].get('red_score', 'N/A')}")

    # Canonical sort order
    DIFF_ORDER = {"easy": 0, "medium": 1, "hard": 2}

    def sort_key(k):
        atype, diff, reward = k
        return (atype, DIFF_ORDER.get(diff, 99), reward)


    # Prepare HELPERS for plotting
    def plot_pairs(metric_blue, metric_red, title, ylabel, filename):
        blue_vals = [averaged[k].get(metric_blue, np.nan) for k in sorted_keys]
        red_vals  = [averaged[k].get(metric_red,  np.nan) for k in sorted_keys]

        x = np.arange(len(sorted_keys))
        width = 0.35

        fig, ax = plt.subplots(figsize=(max(8, len(x)*0.7), 5))

        ax.bar(x - width/2, blue_vals, width, label="Blue", color="tab:blue")
        ax.bar(x + width/2, red_vals,  width, label="Red",  color="tab:red")

        ax.set_xticks(x)
        ax.set_xticklabels(labels, rotation=45, ha="right")
        ax.set_ylabel(ylabel)
        ax.set_title(title, pad=18)
        ax.legend()

        # Add separators and group headers
        add_group_separators(ax, sorted_keys, labels)

        plt.tight_layout()
        outfile = os.path.join(plotdir, filename)
        plt.savefig(outfile)
        plt.close(fig)

    def plot_mixed_pairs(metric_blue1, metric_blue2, metric_blue3, metric_red1, metric_red2, metric_red3, title, ylabel, filename):
        blue_vals = [averaged[k].get(metric_blue1, np.nan) for k in sorted_keys]
        red_vals  = [averaged[k].get(metric_red1,  np.nan) for k in sorted_keys]
        blue_vals2 = [averaged[k].get(metric_blue2, np.nan) for k in sorted_keys]
        red_vals2  = [averaged[k].get(metric_red2,  np.nan) for k in sorted_keys]
        blue_vals3 = [averaged[k].get(metric_blue3, np.nan) for k in sorted_keys]
        red_vals3  = [averaged[k].get(metric_red3,  np.nan) for k in sorted_keys]
        for ind in range(len(blue_vals)):
            blue_vals[ind] += blue_vals2[ind] + blue_vals3[ind]
        for ind in range(len(red_vals)):
            red_vals[ind] += red_vals2[ind] + red_vals3[ind]

        x = np.arange(len(sorted_keys))
        width = 0.35

        fig, ax = plt.subplots(figsize=(max(8, len(x)*0.7), 5))

        ax.bar(x - width/2, blue_vals, width, label="Blue", color="tab:blue")
        ax.bar(x + width/2, red_vals,  width, label="Red",  color="tab:red")

        ax.set_xticks(x)
        ax.set_xticklabels(labels, rotation=45, ha="right")
        ax.set_ylabel(ylabel)
        ax.set_title(title, pad=18)
        ax.legend()

        # Add separators and group headers
        add_group_separators(ax, sorted_keys, labels)

        plt.tight_layout()
        outfile = os.path.join(plotdir, filename)
        plt.savefig(outfile)
        plt.close(fig)
        
    def add_group_separators(ax, keys, labels):
        # Draw vertical lines when agent_type changes
        last_type = None
        for i, k in enumerate(keys):
            atype = k[0]
            if last_type is None:
                last_type = atype
                continue
            if atype != last_type:
                ax.axvline(i - 0.5, color="gray", linestyle="--", linewidth=1, alpha=0.6)
                last_type = atype

        # Add big group labels on top
        centers = {}
        for i, k in enumerate(keys):
            centers.setdefault(k[0], []).append(i)

        ymin, ymax = ax.get_ylim()
        y = ymax * 1.02
        for atype, idxs in centers.items():
            c = sum(idxs) / len(idxs)
            # change atype to agent name (natural language)
            if atype == '0' or atype == 0: 
                atype = "Ultra-defensive"
            elif atype == '1' or atype == 1: 
                atype = "MRHEA"
            elif atype == '2' or atype == 2: 
                atype = "RHEA"
            # set label of grouped bar's
            ax.text(c, y, f"{atype}", ha="center", va="bottom", fontsize=10, fontweight="bold")

    def plot_heatmap(positions, title, filename, bins=BINS, cmap="hot"):#bins=50?
        if not positions:
            return

        xs = [p[0] for p in positions]
        ys = [p[1] for p in positions]

        fig, ax = plt.subplots(figsize=(20, 10))
        ax.set_facecolor('black')

        # Using the hist2d cmap functionality
        h = ax.hist2d(xs, ys, bins=bins, cmap=cmap)
        plt.colorbar(h[3], ax=ax)

        ax.set_title(title)
        ax.set_xlabel("X")
        ax.set_ylabel("Y")

        # Set fixed display area
        ax.set_xlim(0, 160)
        ax.set_ylim(0, 80)

        #fig, ax = plt.subplots(figsize=(6, 1))

        # Add border lines
        ax.axhline(y=0, color='green', linestyle='-', linewidth=3)
        ax.axhline(y=80, color='green', linestyle='-', linewidth=3)
        ax.axvline(x=0, color='green', linestyle='-', linewidth=3)
        ax.axvline(x=80, color='green', linestyle='-', linewidth=1)#middle line
        ax.axvline(x=160, color='green', linestyle='-', linewidth=3)
        plt.tight_layout()
        plt.savefig(os.path.join(plotdir, filename))
        plt.close(fig)

    def plot_box(metric_blue, metric_red, title, ylabel, filename):
        # Candlestick-style plot for blue and red metrics
        data_blue = [averaged[k][metric_blue + '_list'] for k in sorted_keys if averaged[k][metric_blue + '_list']]
        data_red = [averaged[k][metric_red + '_list'] for k in sorted_keys if averaged[k][metric_red + '_list']]

        fig, ax = plt.subplots(figsize=(max(8, len(sorted_keys)*0.7), 5))

        # Positions for boxes (blue on left, red on right for each group)
        positions_blue = [i * 2 for i in range(len(sorted_keys))]
        positions_red = [i * 2 + 1 for i in range(len(sorted_keys))]

        if data_blue:
            ax.boxplot(data_blue, positions=positions_blue, patch_artist=True, 
                       boxprops=dict(facecolor='tab:blue'), widths=0.6)
        if data_red:
            ax.boxplot(data_red, positions=positions_red, patch_artist=True, 
                       boxprops=dict(facecolor='tab:red'), widths=0.6)

        ax.set_xticks([i * 2 + 0.5 for i in range(len(sorted_keys))])
        ax.set_xticklabels(labels, rotation=45, ha="right")
        ax.set_ylabel(ylabel)
        ax.set_title(title)

        # Add separators and group headers
        add_group_separators(ax, sorted_keys, labels)

        plt.tight_layout()
        outfile = os.path.join(plotdir, filename)
        plt.savefig(outfile)
        plt.close(fig)

    # END OF HELPERS


    # prepare plotting directory
    plotdir = os.path.join(foldername, "analysis_plots")
    os.makedirs(plotdir, exist_ok=True)

    # prepare labels and sorted order for consistent plots
    #sorted_keys = sorted(averaged.keys(), key=lambda k: (k[0], k[1], k[2]))
    sorted_keys = sorted(averaged.keys(), key=sort_key)
    #labels = [f"type{k[0]}_{k[1]}_r{k[2]}" for k in sorted_keys]
    labels = []

    for key in sorted_keys:
        atype, diff, reward = key
        # if atype == '0' or atype == 0: 
        #     atype = "Ultra-defensive"
        # elif atype == '1' or atype == 1: 
        #     atype = "MRHEA"
        # elif atype == '2' or atype == 2: 
        #     atype = "RHEA"
        #labels.append(f"{atype} vs {diff}, using reward {reward}")
        labels.append(f"vs {diff}, reward {reward}")

    # Team tri-coverage avg
    plot_pairs(
        "blue_triangle_area", "red_triangle_area",
        title="Tri-Coverage",
        ylabel="area between teammembers",
        filename="tri-coverage.png"
    )

    # Team voronoi-coverage avg
    plot_pairs(
        "blue_voronoi", "red_voronoi",
        title="Voronoi-uniformity Coverage",
        ylabel="uniformity of area (voronoi cells)",
        filename="voronoi-coverage.png"
    )

    # Team tri-coverage avg (changed to candlestick figure)
    plot_box(
        "blue_triangle_area", "red_triangle_area",
        title="Tri-Distance candlestick figure",
        ylabel="area",
        filename="triangle_candle.png"
    )

    # Team mean-dist coverage avg
    plot_pairs(
        "blue_cover_dist", "red_cover_dist",
        title="Mean-Distance Coverage",
        ylabel="avg. distance between teammembers",
        filename="mean-dist-coverage.png"
    )

    # Team side percentage avg
    plot_pairs(
        "blue_sides", "red_sides",
        title="Homebase-Percentage",
        ylabel="avg. percentage of team on own side",
        filename="side_perc.png"
    )

    # Team score per tag (blue_score_per_tag, red_score_per_tag)
    plot_pairs(
        "blue_score", "red_score",
        title="Score (Average)",
        ylabel="flag captures",
        filename="score_avg.png"
    )

    # Team score per tag (blue_score_per_tag, red_score_per_tag)
    plot_pairs(
        "blue_score_per_tag", "red_score_per_tag",
        title="Score per Tag (Blue vs Red)",
        ylabel="score / tag",
        filename="score_per_tag.png"
    )

    # Team defensive average distances
    plot_pairs(
        "blue_def_avg_dist", "red_def_avg_dist",
        title="Defensive Avg Distance (Blue vs Red)",
        ylabel="distance",
        filename="def_avg_dist.png"
    )
    # Team aggressive average distances
    plot_pairs(
        "blue_agr_avg_dist", "red_agr_avg_dist",
        title="Aggressive Avg Distance (Blue vs Red)",
        ylabel="distance",
        filename="agr_avg_dist.png"
    )
    # Team defensive + aggressive average distances
    plot_pairs(
        "blue_defagr_dist", "red_defagr_dist",
        title="Defensive + Aggressive Avg Distance (Blue vs Red)",
        ylabel="distance",
        filename="defAndAgr_avg_dist.png"
    )

    # Team total distances (changed to candlestick figure)
    plot_box(
        "blue_total_dist", "red_total_dist",
        title="Total Distance Traveled (Blue vs Red)",
        ylabel="distance",
        filename="total_dist_candle.png"
    )
    # changed back to bar plot
    # TODO add standard deviation
    plot_pairs(
        "blue_total_dist", "red_total_dist",
        title="Total Distance Traveled (Blue vs Red)",
        ylabel="distance",
        filename="total_dist.png"
    )

    # Combined quantity measure (voronoi + def&agr distance)
    plot_mixed_pairs(
        "blue_voronoi", "red_voronoi", "blue_defagr_dist", "red_defagr_dist", "blue_triangle_area", "red_triangle_area",
                #TODO Add weighting, perhaps change triangle to avg dist.
        title="Combined Voronoi-Convex-DefAndAgrDist. score",
        ylabel="mixed coverage",
        filename="mixed_coverage.png"
    )

    # Heatmaps per experiment configuration
    for key in sorted_keys:
        atype, diff, reward = key
        if atype == '0' or atype == 0: 
            atype = "Ultra-defensive"
        elif atype == '1' or atype == 1: 
            atype = "MRHEA"
        elif atype == '2' or atype == 2: 
            atype = "RHEA"
        label = f"{atype} vs {diff}, using reward {reward}" #TODO this label format for other plots as well

        pos = group_positions[key] #TODO unmoving agents need to be excluded from heatmap.

        """
        Result of the pos[] structure inquiry:
        pos["blue"] -> list of positions
        pos["tag"][integer for experiment number][integer for agent id] -> list of positions
        """
        #print("pos[tag][0]")
        #print(len(pos["tag"]))
        #print(pos["tag"][0])
        #print("pos[tag]")
        #print(type(pos["tag"]))
        #print(pos["tag"])

        #plot heatmap of agent positions:
        plot_heatmap(
            pos["blue"],
            title=f"Blue team positions - {label}",
            filename=f"heatmap_blue_{label}.png",
            #cmap="Berlin"
            cmap = LinearSegmentedColormap.from_list('custom_heatmap', ['black', 'blue', 'cyan', 'white'], N=256) # blue coloring has to be adjusted like this for visibility. red was simpler...
        )
        plot_heatmap(
            pos["red"],
            title=f"Red team positions - {label}",
            filename=f"heatmap_red_{label}.png",
            #cmap="hot"
            cmap = LinearSegmentedColormap.from_list('custom_heatmap', ['black', 'red', 'yellow', 'white'], N=256) #hot worked fine, but background black is beter for consistency
        )


        #plot heatmap of blue agent tag positions:
        bluetags = []
        redtags  = []
        # combine the tag positions from all experiments for blue and red agents (separately)
        for exp_num in pos["tag"]: #range(len(pos["tag"])):
            for agent_id in blue_agents:
                #bluetags.extend(pos["tag"][exp_num].get(str(agent_id), []))
                bluetags = bluetags + exp_num[str(agent_id)]
            for agent_id in red_agents:
                redtags = redtags + exp_num[str(agent_id)]

        #bluetags = pos["tag"][0] + pos["tag"][1] + pos["tag"][2]
        #redtags  = pos["tag"][3] + pos["tag"][4] + pos["tag"][5]
        plot_heatmap(
            bluetags,
            title=f"Blue agent tag positions - {label}",
            filename=f"heatmap_blue_tags_{label}.png",
            bins=TAGBINS,
            cmap = LinearSegmentedColormap.from_list('custom_heatmap', ['black', 'blue', 'cyan', 'white'], N=256)
        )
        #plot heatmap of red agent tag positions:
        plot_heatmap(
            redtags,
            title=f"Red agent tag positions - {label}",
            filename=f"heatmap_red_tags_{label}.png",
            bins=300,
            cmap = LinearSegmentedColormap.from_list('custom_heatmap', ['black', 'red', 'yellow', 'white'], N=256)
        )


    # Optionally print summary of what was done (kept minimal)
    if skipped:
        print(f"Skipped {len(skipped)} files due to errors. See console for details.")
        for fn, err in skipped:
            print(f" - {fn}: {err}")

    return averaged


##############################
if __name__ == "__main__":
    if len(sys.argv) > 1:
        graphicmaker(sys.argv[1])
    #graphicmaker("experiment_results/experiment_5rep_600sec/")
    #graphicmaker("experiment_results/experiment_20260119_210513/")
    else:
        graphicmaker(FOLDER)
        #scancsv(FOLDER)
##############################
